name: Deploy ASP.NET Core 5 application to VPS server

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the project
      run: dotnet publish -c Release -o ./publish

    - name: Copy files to VPS server
      uses: appleboy/scp-action@master
      with:
        host: ${{ "45.76.138.136" }}
        username: ${{ "root" }}
        key: ${{ secrets.AccessServer }}
        source: ./publish/
        target: /var/www/myapp/

    - name: Restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ "45.76.138.136" }}
        username: ${{ "root" }}
        key: ${{ secrets.AccessServer }}
        script: |
          sudo systemctl restart nginx
