name: Deploy ASP.NET Core 5 application to VPS server

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build the project
      run: dotnet build --configuration Release -p:Project=./TestApplication/TestApplication.csproj
      working-directory: ./TestApplication/

    - name: Publish the project
      run: dotnet publish -c Release -o ./publish --no-restore -p:Project=./TestApplication/TestApplication.csproj
      working-directory: ./TestApplication/

    - name: Copy files to VPS server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: publish/
        target: /var/www/MyAPP/

    - name: Restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          sudo systemctl restart nginx
