name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build and publish
        run: dotnet publish -c Release -o publish

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ '45.76.138.136' }}
          username: ${{ 'root' }}
          password: ${{ 'G(7xf8G$ADSX{X=b' }}
          port: 22
          source: ./publish/
          target: /var/www/MyAPP
