name: Deploy ASP.NET Core 5 to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.102
        dotnet-install-dir: ~/.dotnet

    - name: Build application
      run: dotnet build TestApplication.csproj --configuration Release

    - name: Publish application
      run: dotnet publish build TestApplication.csproj --configuration Release --output ./publish

    - name: Install SSH and rsync
      run: sudo apt-get update && sudo apt-get install -y openssh-client rsync

    - name: Deploy to VPS
      uses: easingthemes/ssh-deploy@v2.1.7
      with:
        ssh-private-key: ${{ secrets.ServerAccess }}
        args: -rltgoDzvO --delete ./publish/ user@vps-server:/var/www/MyAPP
